### ISSUE TITLE
making a generic "pre-orthoprofile" ortho-profile

### ISSUE THREAD

**Issue by nh36** [digling/burmish#100]
It would be helpful to run some generic orthoprofile in order to save the annotator time in making an orthography profile. NH will make a spreadsheet to this effect and send it to JML.

**Comment by nh36** [comment]
[pre-ortho.zip](https://github.com/digling/burmish/files/841605/pre-ortho.zip)
The spreadsheet is in this attachment. I have tried to include only those substitutions that I think are safe to do on any dataset. The one that might be a bit dangerous is j > dʒ, but my thought is that it can always be undone if it causes problems. If you know for sure that a dataset is perfect iPA then you wouldn't apply this pre-orthoprofile anyhow.

**Comment by LinguList** [comment]
please check out [here](https://github.com/digling/burmish/tree/master/profiles) and modify from there.

**Comment by LinguList** [comment]
I suppose we can dynamically load specific of these instances by applying some flags. E.g., if you write me things like "ignore line X", I can ignore this line in loading the profile.
