### ISSUE TITLE
Question marks appearing in unexpected places in automatic reconstruction

### ISSUE THREAD

**Issue by nh36** [digling/burmish#102]
If you look at COGIDS 13, 137, 143, etc. there are initial segments that are unanimously or nearly unanimously agreed upon and it is a surprise that the system is not reconstructing them.

**Comment by LinguList** [comment]
There must be still a bug in the software, but I do really not know where. The algorithm is told to strike if the pattern is not recognized. Maybe it's not the initial but the vowels, and here, I should change the algo in such a way that it still reconstructs the rest...

**Comment by LinguList** [comment]
But I guess that's really the point: one fails, and I coded it in such a way that all fail, which is of course not what we want...

**Comment by nh36** [comment]
Mattis fixed this bug this morning.
