### ISSUE TITLE
character y in Hpun

### ISSUE THREAD

**Issue by nh36** [digling/burmish#11]
Initial y in Hpun appears to be understood as a vowel, whereas it clearly means [j]. For example, 

323	Atsi	hundred	ʃo⁵¹	ʃ o ⁵¹ 	63
324	Bola	hundred	ja⁵⁵	j a ⁵⁵  	63
325	Burmese_ZMYYC	hundred	rā	r ā 	63
326	Hpun	hundred	yɑh¹	 y ɑ h ¹ 	63
327	Hpun	hundred	yáh	y á h 	63
328	Hpun	hundred	yáʔ	 y á ʔ 	63
329	Maru	hundred	jɔ³¹	 j ɔ ³¹ 	63

**Comment by LinguList** [comment]
closing this for the moment, since hpun is anyway not providing enough coverage
