### ISSUE TITLE
Written Burmese Sound Check

### ISSUE THREAD

**Issue by LinguList** [digling/burmish#27]
https://github.com/digling/burmish/blob/master/sounds/sounds.md#written-burmese

**Comment by nh36** [comment]
As I have explained Written Burmese in this transcription is not linguistically meaningful. It would be better to actually convert the data to Burmese and then proceed from there. 
To be clear, these conversions are NOT to IPA, but to Burmese, which then would have to be converted to IPA according to the phoneme check under Burmese. 
ɑ > a
s > c
sh > ch
tθ > s
ɑɑ > ā
ɑi > ai 
ŋ > ṅ
ʰ > h 
hn > nh 
hr > rh 
hm > mh 
hl > lh 
hŋ > ṅh 
hȵ > ñh
w > v
ȵ > ñ
If those substitutions were made I would have to look over the results the spot check the remaining symbols in context.

**Comment by LinguList** [comment]
Allright, I'll have a look at how the conversion works with this
information. More later from me on that, thanks!
