### ISSUE TITLE
Xiandou Sound Check

### ISSUE THREAD

**Issue by LinguList** [digling/burmish#31]
https://github.com/digling/burmish/blob/master/sounds/sounds.md#xiandao

**Comment by nh36** [comment]
You feel comfortable interpreting a breve in ă which you identify with v126. So it seems like ɔ̆ should not in principle be a problem for you. ɔ̆ is one of the only two missing sounds for this language. The other ɲ̇, I assume is a typo. We should check the original publication.

**Comment by LinguList** [comment]
The breve is the "legacy" data I used to create the initial list, which
is not complete, since it was created on the data people had in the
P-Base project, but, yes, since it is an IPA symbol allowing to assign
things as "ultra-short", ultra-short ɔ̆ should also be added to the list,
and this is on the Cross-Linguistic Linguistic Alphabet, to make sure
the symbol is there.
