### ISSUE TITLE
Marma data is very sparse, should we leave it or are there other sources?

### ISSUE THREAD

**Issue by LinguList** [digling/burmish#36]
The matches for Marma are even beyond that for Hpun, which is incredible, given the number of 600 words in the source.

Here's the semi-automatic matching:

* https://github.com/digling/burmish/blob/master/tsv/marma.matches.tsv

And here's the link to the original concepts:

* https://github.com/digling/burmish/blob/master/tsv/marma.concepts.tsv

**Comment by nh36** [comment]
I have confirmed that Marma is a Burmese dialect. A comparative
reconstruction of the Burmese dialects would be an interesting project in
its own right, but I don't think we should do that just now, so best to
leave Marma out.

Nathan

--
Dr Nathan W. Hill
Reader in Tibetan and Historical Linguistics
Department of China & Inner Asia and Department of Linguistics
SOAS, University of London
Thornhaugh Street, Russell Square, London WC1H 0XG, UK
Tel: +44 (0)20 7898 4512

--
Profile -- http://www.soas.ac.uk/staff/staff46254.php
Tibetan Studies at SOAS -- http://www.soas.ac.uk/cia/tibetanstudies/
--
