### ISSUE TITLE
Create automatic morpheme parse of data for cross-concept morpheme annotation

### ISSUE THREAD

**Issue by LinguList** [digling/burmish#37]
This should be done for all languages, so that these annotations can later be refined. Annotation will be the classical one with identifiers for morphemes. Ideally, this can be done int he EDICTOR app. If this does not work quickly enough to add this part to the program, it can also be done in spreadsheet, or in EDICTOR, but without the help of a specific extra-app.

**Comment by nh36** [comment]
I think this thread can probably be closed.
