### ISSUE TITLE
Think of additional 150-200 concepts to be later added to the data

### ISSUE THREAD

**Issue by LinguList** [digling/burmish#38]
This is not of any urgency, but adding some more concepts may be useful at some point, so let's not forget about it.

As a starting idea for exploration of potentially useful concepts, I recommend the list by Sattherthwaie Phillips:
* https://github.com/clld/concepticon-data/blob/master/concepticondata/conceptlists/SatterthwaitePhillips-2011-423.tsv

**Comment by LinguList** [comment]
As an example, we might take "bat", since it seems to be a good STB root, as Guillaume Jacques points out [here](https://panchr.hypotheses.org/885). So it would be interesting how it is represented in Burmish (borrowed from Chinese, etc.).

Having 150 of these proposals for "useful" concepts will help us to increase the data rapidly and also check for interesting connections across words and morphemes.

One further criterion would be to look at concepts which are almost entirely expressed with two morphemes and list the missing ones (we lack "day", for example, since we have "sun", but not all Burmish languages have the same word for "day" and for "sun", as can be seen from words like "yesterday" in our sample), so we should add "day", etc.

**Comment by nh36** [comment]
We have finished this now. We have circa 500 concepts in the system.
