### ISSUE TITLE
Add missing words for Old Burmish?

### ISSUE THREAD

**Issue by LinguList** [digling/burmish#41]
Currently, there are some 130 items for Old Burmish.

The question is: is it feasible to add the full 250 words, potentially with help from experts?

If so, there are different ways to do it:

1. via spreadsheet that I prepare along with concept definitions, in order to make sure that the translations are as close as possible (I'll base it on [this sheet](https://github.com/digling/burmish/blob/master/tsv/STDB-2016-250.tsv)), or
2. via the EDICTOR app, where I have the possibility to create "templates", in which empty slots are automatically created and can then be filled in.

**Comment by nh36** [comment]
Partly it depends on how you wish to proceed. In principle, if there is a
'Written Burmese' then this can mechanically be changed into Burmese. This
in turn, can also be mechanically changed into Old Burmese. But I often
times found myself uncomfortable doing this, but in any case, I can make an
effort to add Burmese and Old Burmese. I suggest that the best way is
through the Edictor system.



--
Dr Nathan W. Hill
Reader in Tibetan and Historical Linguistics
Department of China & Inner Asia and Department of Linguistics
SOAS, University of London
Thornhaugh Street, Russell Square, London WC1H 0XG, UK
Tel: +44 (0)20 7898 4512

--
Profile -- http://www.soas.ac.uk/staff/staff46254.php
Tibetan Studies at SOAS -- http://www.soas.ac.uk/cia/tibetanstudies/
--

**Comment by LinguList** [comment]
Allright. As I just said in #43, this will require to have the web-app updated (I mean the interface for selection of languages at http://dighl.github.io/burmese/), so that we can then just use the "template" flag in the Edictor. I'll try to prepare this quickly.
