### ISSUE TITLE
Burmese Sound Check

### ISSUE THREAD

**Issue by LinguList** [digling/burmish#42]
As an alternative to Written Burmese, Burmese could also be used, where another transcription was originally employed.

https://github.com/digling/burmish/blob/master/sounds/sounds.md#burmese

A problem is, however, that there are apparently not enough words in the 250 word list. Currently, there are only about 50 matching, so the remaining ones would need to be re-introduced. There are more words for other concepts, but not in the list we now decided for.

**Comment by nh36** [comment]
In Burmese y is [j] c564 not [y] v166.

**Comment by nh36** [comment]
In Burmese ṅ is [ŋ] c795

**Comment by nh36** [comment]
Burmese nh nʰ c096, mh mʰ c243, and lh lʰ c541 are incorrect identifications. These should be identified as voiceless rather than aspirated. m̥ c235, l̥ c538

**Comment by nh36** [comment]
In Burmese c refers [ts] c015 and not to [c] c600.

**Comment by nh36** [comment]
About your original comment. I can very easily convert any 'Written Burmese' into 'Burmese' for missing comments.
