### ISSUE TITLE
Proto-North-West-Burmish by Mann

### ISSUE THREAD

**Issue by LinguList** [digling/burmish#45]
Add these items to our current 250 word list (only 174 overlapping, but better than nothing, and when expanding the list later, we can add more from Mann's original list).

Here again, the best is a probably a template with the Edictor, but typing data off may again be easier when just typing it off instead of looking word by word, so @nh36, let me know what you prefer, an empty template with the Edictor, where words can be inserted, or just a spreadsheet from Mann.

BTW: for clarification, I mean the data on page 125f, where he shows reconstructed words, which is better than reconstructed syllables, since, as you can see from the data in Mann, we can't back to his original words, since he only presents the syllables...

**Comment by nh36** [comment]
I am not sure how useable his reconstructions are with their {} and V and
C. It seems to me our time would be better spent to just come up with our
own reconstructions. But, I will allow myself to be convinced otherwised
and would be happy to rekey them. I think this would be easier to do in a
spreadsheet.

best,
Nathan

--
Dr Nathan W. Hill
Reader in Tibetan and Historical Linguistics
Department of China & Inner Asia and Department of Linguistics
SOAS, University of London
Thornhaugh Street, Russell Square, London WC1H 0XG, UK
Tel: +44 (0)20 7898 4512

--
Profile -- http://www.soas.ac.uk/staff/staff46254.php
Tibetan Studies at SOAS -- http://www.soas.ac.uk/cia/tibetanstudies/
--

**Comment by LinguList** [comment]
My idea having them is first for quick reference regarding alternatives,
then, I wanted to give Mann anyway a closer read since he is dealing
with compounding to some degree, and he has some criteria on the words
he proposes for PNB. His morpheme collections are unfortunately mostly
useless, unless we can verify and re-identify them in the data in real
words (it's strange but it's similar to those huge collections of
Chinese character readings in the dialects where one does not know
whether it's an actually spoke word or something else). Siince in this
very list, Mann takes the "most frequently occuring compounds" and
reconstructs the word accordingly, this might be interesting to compare
with the alternative data, not regarding the reconstructions in detail,
but more regarding the morphemes he picks...

But it's no matter of urgency, I'm just trying to collect all kinds of
things there are out in the wild.
