### ISSUE TITLE
Bola Morpheme Indication

### ISSUE THREAD

**Issue by LinguList** [digling/burmish#50]
Please use [this link](https://dighl.github.io/burmish) for selecting Bola, and follow [the rules for annotation](https://github.com/digling/burmish/blob/master/morphemes/morphemes.md), as well as the information in [colexification](https://github.com/digling/burmish/blob/master/morphemes/colexifications.md) and [colexification in the language](https://github.com/digling/burmish/blob/master/morphemes/morphemes.md#morpheme-information-for-bola).

**Comment by nh36** [comment]
I have tried to load the link in several browsers and it is not happening.
I don't think it is my connection, can you please check and confirm?

--
Dr Nathan W. Hill
Reader in Tibetan and Historical Linguistics
Department of China & Inner Asia and Department of Linguistics
SOAS, University of London
Thornhaugh Street, Russell Square, London WC1H 0XG, UK
Tel: +44 (0)20 7898 4512

--
Profile -- http://www.soas.ac.uk/staff/staff46254.php
Tibetan Studies at SOAS -- http://www.soas.ac.uk/cia/tibetanstudies/
--

**Comment by LinguList** [comment]
So to clarify, I can't put full links on github, since they are somehow converted, so that the edictor won't recognize them anymore, so preferred way is going over the html interface at http://dighl.github.io/burmish.

**Comment by LinguList** [comment]
Now, I uploaded what I call "morpheme profiles". This is a specific tabular view that shows all colexified words with their concepts for a word one wants to investigate. Data for Bola is at this link:

* https://github.com/digling/burmish/blob/master/morphemes/profiles.md#morpheme-profiles-for-taxon-bola

It take some time to get used to this view, but it helps to assemble all the different parts with whom a word shares morphemes along with the orignal concepts for mropheme analysis.
