### ISSUE TITLE
crossbow

### ISSUE THREAD

**Issue by nh36** [digling/burmish#56]
I strongly suspect that most of the words that are under 'crossbow' actually just mean 'bow'. This is something to look into.

**Comment by LinguList** [comment]
I just checked TBL: it is 弓, that is, "bow", no cross-bow. 

This can be changed. The error is by the way only OUR gloss in the data, as STEDT also lists "bow (for arrow)", and concepticon_id is just "bow".

**Comment by LinguList** [comment]
I just modified manually.
