### ISSUE TITLE
manual reconstructions for correspondence patterns

### ISSUE THREAD

**Issue by LinguList** [digling/burmish#59]
based on the initial pattern analysis, create patterns for the reconstruction.

**Comment by nh36** [comment]
I have now made a reasonable stab at this in the google doc. For the initials and finals it was easy for the vowels and tones I have only done the cases that seemed quite safe to me.

**Comment by LinguList** [comment]
well done! I'll try and solve the clique-inconsistencies around Monday
and then hopefully find the time to work on the first version of the
automatic reconstruction so that we can see how well this works. I'm
extremely curious, how many fuzzy variants we will find, where, e.g., we
cannot say whether it was kh or k, etc. But I'll try to have a solid
code base for this: better to wait a few days longer than having sloppy
ad-hoc results that need to be refined later anyway.
