### ISSUE TITLE
finalize bibliography (set it up) in bibtex

### ISSUE THREAD

**Issue by LinguList** [digling/burmish#66]
and upload later on github, in a new folder references/bibliography.bib

**Comment by nh36** [comment]
It might be overstating things to say that the bibliography is now, but in
any event there is a lot in there now and it is in a pretty good state. I
will add more things as they are needed concretely.

I have also started to write the literature review in the Latex document. I
am not gearing it toward the QPA paper, but rather just putting in as much
as I can. This will at least be used in the final book.

--
Dr Nathan W. Hill
Reader in Tibetan and Historical Linguistics
Department of China & Inner Asia and Department of Linguistics
SOAS, University of London
Thornhaugh Street, Russell Square, London WC1H 0XG, UK
Tel: +44 (0)20 7898 4512

--
Profile -- http://www.soas.ac.uk/staff/staff46254.php
Tibetan Studies at SOAS -- http://www.soas.ac.uk/cia/tibetanstudies/
--

**Comment by LinguList** [comment]
Yep, I saw it, excellent! I'll at some point start putting the
literature into a references/-folder to the github, but I'll wait until
I decided how to re-arrange the current github repo, as with the new
ideas, like orthoprofiles, more datasets, etc., things can be handled
more transparently there.
