### ISSUE TITLE
clean the directory

### ISSUE THREAD

**Issue by LinguList** [digling/burmish#68]
we have too many dead ends, this needs to be cleaned and only senseful things should be retained.

**Comment by LinguList** [comment]
Basic and crucial point will be now to model the data structure similar to the one used for [cddb](http://github.com/digling/cddb). It seems that this is much more efficient in maintaining the structure.

**Comment by nh36** [comment]
Is this issue still live?

**Comment by LinguList** [comment]
more or less, yes, but let's close it for the moment, as we're advancing (you may not have realised, but it's easier for me to quickly code the stuff now, like orthography profiles and concepticon).
