### ISSUE TITLE
Refine Automatic Alignment Analysis

### ISSUE THREAD

**Issue by LinguList** [digling/burmish#73]
expanded nasals (write ã as ã~) are useful for us, but this was not applied ot all words in Rangoon, creating a new pattern in coda, which is surely not the wanted one.

**Comment by LinguList** [comment]
there are more issues, but partially resolved:
* medials are wrongly identified, or badly aligned, etc.
* some strange vowels are aligned in medial position
Most of them can be handled by adjusting the alignment parameters in automatic alignment, using a more specific model for Burmese. This is already prepared now and will be added soon.

**Comment by nh36** [comment]
I have manually fixed the tilde problem. I believe.

**Comment by nh36** [comment]
I believe I have fixed this with all of them now having tilde's.

**Comment by LinguList** [comment]
I think, with the representation of syllable "structures" we don't need the automatic alignment anymore (just a method that produces alignments from the data, but even THAT may not be needed, as the QPA could be adjusted accordingly).
