### ISSUE TITLE
the handling of tense vowels

### ISSUE THREAD

**Issue by nh36** [digling/burmish#9]
We discussed this before (but at least I can practice with the GitHub interface) and perhaps it is not a problem to solve at the level of tozenizing. But here goes, etymologically speaking tense vowels function as part of the initial. Notice in the cognates below how Burmese kh- is cognate to k _ in Bola and Lashi, and how Achang and Xiandao l̥ is cognate with l _ Bola and Maru. Perhaps it would be good to tokenize the _ as part of the initial, but this might be quite tricky (since it would have to jump over a vowel and a glide in some cases). Perhaps it is better solved later in the work flow. 

ID  DOCULECT    CONCEPT IPA TOKENS  CLUSTERID
121 Xiandao dry tsui³⁵    ts ui ³⁵    38
122 Atsi    dry xui⁵⁵    x ui ⁵⁵    32
123 Bola    dry kja̱uʔ⁵⁵  k j a̱u ʔ ⁵⁵  32
124 Burmese_ZMYYC   dry khrok kh r o k  32
125 Hpun    dry xàʔ  x à ʔ    32
126 Hpun    dry xòʔ  x ò ʔ    32
127 Maru    dry fai⁵⁵   f ai ⁵⁵     32
128 Lashi   dry kju̱ːʔ⁵⁵ k j u̱ː ʔ ⁵⁵ 32
129 Maru    dry tjaù' t j aù '  32
130 Achang_Longchuan    dry l̥ap⁵⁵  l̥ a p ⁵⁵     31
131 Xiandao dry l̥ap⁵⁵ l̥ a p ⁵⁵  31
132 Atsi    dry jaŋ²¹    j a ŋ ²¹     35
133 Bola    dry lɛ̱ʔ⁵⁵   l ɛ̱ ʔ ⁵⁵    31
134 Maru    dry lɛ̱ʔ⁵⁵   l ɛ̱ ʔ ⁵⁵    31
135 Lashi   dry jaːŋ³³   j aː ŋ ³³  35

**Comment by LinguList** [comment]
Allright, this is important now. Ideally, I would like to have a phonetic way to represent it, so we can map it with my CLPA. If this does not work, we can ignore the tenseness in the CLPA link, but leave it in the symbol (the idea is, that we add CLPA-identifiers to any sound in the tokenized data, in this way, we can keep additional data, but say that we do not map it to CLPA).

Ideally, @nh36 , provide me with some ideas on how these could be represented (breathy, creaky, whatever), and I'll either add the vowels to CLPA, if the phonetic representation is consistent and "real", or I'll map them to the normal vowels.

**Comment by nh36** [comment]
Dear Mattis,

I attach Anton Lustig's description of creaky phonation in Zaiwa. He marks
this as v in the practical orthography. It is what the Chinese authors mark
with a dot or line under the vowel.

In Robbins Burling's work he heard the same phenomenon as preglottalization
of the initial, which I find a very convenient understanding for historical
purposes.

--
Dr Nathan W. Hill
Reader in Tibetan and Historical Linguistics
Department of China & Inner Asia and Department of Linguistics
SOAS, University of London
Thornhaugh Street, Russell Square, London WC1H 0XG, UK
Tel: +44 (0)20 7898 4512

--
Profile -- http://www.soas.ac.uk/staff/staff46254.php
Tibetan Studies at SOAS -- http://www.soas.ac.uk/cia/tibetanstudies/
--

**Comment by nh36** [comment]
According to Wikipedia the way to represent creaky phonation is with a tilde beneath a letter, e.g. [d̰]. So, one approach would be for you to switch the line that occur in the data into a tilde below the letter and then to add all of the resulting monsters into your list of IPA symbols. I guess this tack would have the advantage of making the symbols available for other languages too. But, I note, these things are probably best seen as effecting the whole syllable and not just the vowel. But but, maybe it is best for you to treat them segmentally to have a way to handle them, and then to worry about supersegmentals in general on another occasion.

**Comment by LinguList** [comment]
CLPA distinguishes creaky vowels and creaky consonants, using the same
annotation, and I saw it also in Austro-Asiatic data, that they put the
little "Kringel" under the vowel symbol, and it is already in the
current legacy data, so this is probably easier then going for a
full-syllable perspective. Since there is syllable-segmentation, and
this CLPA stores creakyness, it's no problem to later check for effects
of creaky-ness in sound correspondences, even if it's on one segment,
but correlates with others.

**Comment by nh36** [comment]
In that case, I think you can do a global change in our data from the
underline to the Kringel, but if it is useful I will list all cases under
the relevant doculect.

(We must however keep in mind that our creaky interpretation is based on
Lustig's description of Atsi, so may not be phonetically correct for all
languages.)

--
Dr Nathan W. Hill
Reader in Tibetan and Historical Linguistics
Department of China & Inner Asia and Department of Linguistics
SOAS, University of London
Thornhaugh Street, Russell Square, London WC1H 0XG, UK
Tel: +44 (0)20 7898 4512

--
Profile -- http://www.soas.ac.uk/staff/staff46254.php
Tibetan Studies at SOAS -- http://www.soas.ac.uk/cia/tibetanstudies/
--

**Comment by LinguList** [comment]
Given that we store the original IPA, we can theoretically always go
back. And I'll also store the segmented IPA, so we can even directly go
back, since we'll track position of a segment, and what we represent it
as (notwithstanding erroneous annotations, etc., but pretty save).

**Comment by nh36** [comment]
Here is the description from Nishi 1999. It is pretty clear that all languages make both vowel and initial creaky, it is fine for us to represent it as creaky vowels. 
[Pages from Nishi 1999 four papers on burmese.pdf](https://github.com/digling/burmish/files/150074/Pages.from.Nishi.1999.four.papers.on.burmese.pdf)

**Comment by LinguList** [comment]
okay, this can be handled via orthoprofiles now.
